### ISSUE TITLE
Error when searching for something that isn't in a message

### ISSUE THREAD

**Issue by Frozenfire92** [cloudson/gitql#20]
When doing a command like

```
gitql "select hash, message from commits where 'hasdfjk' in message order by date asc"
```

I get

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x5a5d20, 0xc820010170)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/cloudson/gitql/runtime.walkCommits(0xc82000a560, 0xc820053e50)
        /home/joel/Go/src/github.com/cloudson/gitql/runtime/commits.go:58 +0x42e
github.com/cloudson/gitql/runtime.Run(0xc82000a560)
        /home/joel/Go/src/github.com/cloudson/gitql/runtime/runtime.go:79 +0x15f
main.main()
        /home/joel/Go/src/github.com/cloudson/gitql/gitql.go:29 +0x372
```

This should fail more gracefully

**Comment by cloudson** [comment]
Sorry for the late @Frozenfire92 . I found the problem that you mentioned here and fixed it. 
Now, gitql will return a empty table as result. We can discuss about a new way to show results in cases like that. 
Thank you for report.
